local day06 = require("day06")

describe("day06", function()
    it("solves the example", function()
        local input = [[....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
]]
        local part1, part2 = day06.solve(input)
        assert.are.equal(41, part1)
        assert.are.equal(6, part2)
    end)
end)
