local day08 = require("day08")

describe("day08", function()
    it("solves the example", function()
        local input = [[............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
]]
        local part1, part2 = day08.solve(input)
        assert.are.equal(14, part1)
        assert.are.equal(34, part2)
    end)
end)
