name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: busted
        uses: lunarmodules/busted@v2
        with:
          args: --verbose src
      - name: luacheck
        uses: lunarmodules/luacheck@v1
