name: ci
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run make -p luajitPackages.luacheck luajitPackages.busted stylua gnumake
      - run: git diff --exit-code
